name: 'Pinky Generator'
description: 'Generator for Flutter Pinky github action'
branding:
  icon: 'git-merge'
  color: 'white'
  
inputs:
  path:
    description: 'Path to file'
    required: true
  slack_token: 
    description: 'Slack token'
    required: false
  telegram_token: 
    description: 'Telegram token'
    required: false
  telegram_chat_id:
    description: 'Telegram chat id'
    required: false
  
  channel:
    description: 'Slack channels'
    required: false
  filename: 
    description: 'Filename of file'
    required: false
  filetype:
    description: 'A file type identifier.'
    required: false
  comment:
    description: 'The message text introducing the file in specified channels.'
    required: false

  webhook_url:
    description: 'The webhook url to send the message to.'
    required: false

  usePicky:
   description: 'Indicate either you wanna use our picky bot'
   required: false

outputs:
  slack_result: # id of output
    description: 'Output from slack'

runs:
  using: 'node16'
  main: 'dist/index.js'